general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18.0


[font.bold]
family = "MesloLGS NF"
# family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
# family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
# family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"



[window]
dimensions = { columns = 160, lines = 48 } 
padding.x = 2
padding.y = 0
opacity = 1

