#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#!/usr/bin/env bash

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# config
yabai -m config layout bsp
yabai -m config top_padding    8
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8
yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off


function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 web
setup_space 2 code
setup_space 3 social
setup_space 4 other


# Configure the correct spaces for applications
yabai -m rule --add app="^(Arc|Chrome|Zen|Firefox|Safari)$" space=^1
yabai -m rule --add app="^(iTerm|Terminal|Alacritty|kitty|WezTerm|Ghostty)$" space=^2
yabai -m rule --add app="^(Teams|Outlook|Slack)$" space=^3
yabai -m rule --add app="^(Spotify|Discord|TablePlus|Notes)$" space=^4

echo "yabai configuration loaded.."
